on:
  push:
    tags:
      - "*"

name: release

jobs:
  compare:
    name: compare
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: "npm install -g deno"
      - run: "npm ci --ignore-scripts"
      - run: "npm run compile"
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./src/wasm/pkg/
      - run: "npm diff --diff=$(jq -r '.name' package.json)@$(jq -r '.version' package.json)"
      - run: "[[ -z $(npm diff --diff=$(jq -r '.name' package.json)@$(jq -r '.version' package.json)) ]]"
      - run: "deno bundle --minify --output local ./src/node/mod.ts"
      - run: "deno bundle --minify --output remote https://jsr.io/$(jq -r '.name' deno.json)/$(jq -r '.version' deno.json)/src/node/mod.ts"
      - run: "diff local remote"
      - run: "[[ -z $(diff local remote) ]]"
